/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hdt6;

import java.util.Map;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author sevic69
 */
public class CVista extends javax.swing.JFrame implements ObservadorColeccion, ObservadorCartas
{
    protected CControlador controlador;
    protected CModelo modelo;
    
    /**
     * Creates new form CVista
     */
    public CVista(CModelo m, CControlador c) 
    {
        controlador = c;
        modelo = m;
        modelo.registrarObservadorColeccion(this);
        modelo.registrarObservadorCartas(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Cartas = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Coleccion = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_Cartas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_Cartas);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 3, 487, 490));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HashMap", "LinkedHashMap", "TreeMap" }));
        jPanel5.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 57, -1, -1));

        jLabel2.setText("Escoger Implementacion");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 23, -1, -1));

        jButton2.setText("Escoja");
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 101, -1, -1));

        jTabbedPane2.addTab("Cartas", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_Coleccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Coleccion);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, 480));
        jPanel6.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 43, 240, -1));

        jButton1.setText("Buscar");
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, -1));

        jButton3.setText("Agregar");
        jPanel6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, -1, -1));

        jLabel1.setText("Agregar a mi coleccion");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        jTabbedPane2.addTab("Mi Coleccion", jPanel6);

        jPanel4.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 510));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable_Cartas;
    private javax.swing.JTable jTable_Coleccion;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizarColeccion(Map<String, Integer> map) {
        jTable_Coleccion.setModel(new TablaColeccion(map));
        jTable_Coleccion.setAutoCreateRowSorter(true);
        
    }

    @Override
    public void actualizarCartas(Map<String, String> map) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    class TablaColeccion extends AbstractTableModel
    {
        
        Object[][] datos;
        Map<String, Integer> _map;
        String[] nombreColumnas = {"Nomnbre", "Tipo", "Cantidad"};
        
        TablaColeccion(Map<String, Integer> map)
        {
            _map = map;
            int i = 0;
            for(String llave: map.keySet())
            {
                datos[i][0] = llave;
                datos[i][1] = modelo.buscarTipo(llave);
                datos[i][2] = map.get(llave);
                i++;
            }
        }
        
        

        @Override
        public int getRowCount() {
            return _map.size();
        }

        @Override
        public int getColumnCount() {
            return nombreColumnas.length;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            return datos[rowIndex][columnIndex];
        }
        
    }
    
    class TablaCartas extends AbstractTableModel
    {
        
        Object[][] datos;
        Map<String, Integer> _map;
        String[] nombreColumnas = {"Nomnbre", "Tipo"};
        
        TablaCartas(Map<String, Integer> map)
        {
            _map = map;
            int i = 0;
            for(String llave: _map.keySet())
            {
                datos[i][0] = llave;
                datos[i][1] = _map.get(llave);
                i++;
            }
        }

        @Override
        public int getRowCount() {
            return _map.size();
        }

        @Override
        public int getColumnCount() {
            return nombreColumnas.length;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            return datos[rowIndex][columnIndex];
        }
        
    }
        
}
