/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hdt6;

import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author sevic69
 */
public class CVista extends javax.swing.JFrame implements ObservadorColeccion, ObservadorCartas
{
    protected CControlador controlador;
    protected CModelo modelo;
    
    /**
     * Creates new form CVista
     */
    public CVista(CModelo m, CControlador c) 
    {
        controlador = c;
        modelo = m;
        modelo.registrarObservadorColeccion(this);
        modelo.registrarObservadorCartas(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Cartas = new javax.swing.JTable();
        jCmbBox_Implementacion = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jBtn_EscogerImplementacion = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Coleccion = new javax.swing.JTable();
        jTField_NombreCarta = new javax.swing.JTextField();
        jBtn_BuscarCarta = new javax.swing.JButton();
        jBtn_AgregarCarta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_Cartas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_Cartas);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 3, 487, 490));

        jCmbBox_Implementacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HashMap", "LinkedHashMap", "TreeMap" }));
        jPanel5.add(jCmbBox_Implementacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 57, -1, -1));

        jLabel2.setText("Escoger Implementacion");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 23, -1, -1));

        jBtn_EscogerImplementacion.setLabel("Escoger");
        jBtn_EscogerImplementacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_EscogerImplementacionMouseClicked(evt);
            }
        });
        jPanel5.add(jBtn_EscogerImplementacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 101, -1, -1));

        jTabbedPane2.addTab("Cartas", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_Coleccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Coleccion);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, 480));

        jTField_NombreCarta.setEnabled(false);
        jPanel6.add(jTField_NombreCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 43, 240, -1));

        jBtn_BuscarCarta.setText("Buscar");
        jBtn_BuscarCarta.setEnabled(false);
        jBtn_BuscarCarta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_BuscarCartaMouseClicked(evt);
            }
        });
        jPanel6.add(jBtn_BuscarCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, -1));

        jBtn_AgregarCarta.setText("Agregar");
        jBtn_AgregarCarta.setEnabled(false);
        jBtn_AgregarCarta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_AgregarCartaMouseClicked(evt);
            }
        });
        jPanel6.add(jBtn_AgregarCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, -1, -1));

        jLabel1.setText("Agregar a mi coleccion");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        jTabbedPane2.addTab("Mi Coleccion", jPanel6);

        jPanel4.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 510));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_EscogerImplementacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_EscogerImplementacionMouseClicked
        controlador.escogerImplementacion(
                jCmbBox_Implementacion.getSelectedIndex());
        jTField_NombreCarta.setEnabled(true);
        jBtn_AgregarCarta.setEnabled(true);
        jBtn_BuscarCarta.setEnabled(true);
    }//GEN-LAST:event_jBtn_EscogerImplementacionMouseClicked

    private void jBtn_AgregarCartaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_AgregarCartaMouseClicked
        try
        {
            controlador.agregarCartaAColeccion(jTField_NombreCarta.getText());
        }
        catch(IllegalStateException e) 
        {
            // show error dialog
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jBtn_AgregarCartaMouseClicked

    private void jBtn_BuscarCartaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_BuscarCartaMouseClicked
        try
        {
            String tipo = controlador.buscarTipo(jTField_NombreCarta.getText());
        }
        catch(IllegalStateException e) 
        {
            // show error dialog
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jBtn_BuscarCartaMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_AgregarCarta;
    private javax.swing.JButton jBtn_BuscarCarta;
    private javax.swing.JButton jBtn_EscogerImplementacion;
    private javax.swing.JComboBox<String> jCmbBox_Implementacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTField_NombreCarta;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable_Cartas;
    private javax.swing.JTable jTable_Coleccion;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizarColeccion(Map<String, Integer> map) {
        jTable_Coleccion.setModel(new TablaColeccion(map));
        jTable_Coleccion.setAutoCreateRowSorter(true);
        
    }

    @Override
    public void actualizarCartas(Map<String, String> map) {
        jTable_Cartas.setModel(new TablaCartas(map));
        jTable_Cartas.setAutoCreateRowSorter(true);
    }
    
    class TablaColeccion extends AbstractTableModel
    {
        
        Object[][] datos;
        Map<String, Integer> _map;
        String[] nombreColumnas = {"Nombre", "Tipo", "Cantidad"};
        
        TablaColeccion(Map<String, Integer> map)
        {
            _map = map;
            datos = new Object[_map.size()][nombreColumnas.length];
            int i = 0;
            for(String llave: map.keySet())
            {
                datos[i][0] = llave;
                datos[i][1] = modelo.buscarTipo(llave);
                datos[i][2] = map.get(llave);
                i++;
            }
        }
        
        

        @Override
        public int getRowCount() {
            return _map.size();
        }

        @Override
        public int getColumnCount() {
            return nombreColumnas.length;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            return datos[rowIndex][columnIndex];
        }
        
        @Override
        public String getColumnName(int index)
        {
            return nombreColumnas[index];
        }
        
    }
    
    class TablaCartas extends AbstractTableModel
    {
        
        Object[][] datos;
        Map<String, String> _map;
        String[] nombreColumnas = {"Nombre", "Tipo"};
        
        TablaCartas(Map<String, String> map)
        {
            _map = map;
            datos = new Object[_map.size()][nombreColumnas.length];
            int i = 0;
            for(String llave: _map.keySet())
            {
                datos[i][0] = llave;
                datos[i][1] = _map.get(llave);
                i++;
            }
        }

        @Override
        public int getRowCount() 
        {
            return _map.size();
        }

        @Override
        public int getColumnCount() 
        {
            return nombreColumnas.length;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) 
        {
            return datos[rowIndex][columnIndex];
        }
        
        @Override
        public String getColumnName(int index)
        {
            return nombreColumnas[index];
        }
        
    }
        
}
